### ISSUE TITLE
The remote server returned an error: (501) Not Implemented.

### ISSUE THREAD

**Issue by ZeRoZeRoRaZ** [Entonsky/GooglePhotoOrganizer#6]
Google.GData.Client.GDataRequestException occurred
  HResult=0x80131500
  Message=Execution of request failed: https://picasaweb.google.com/data/feed/api/user/default
  Source=Google.GData.Client
  StackTrace:
   at Google.GData.Client.GDataRequest.Execute()
   at Google.GData.Client.Service.EntrySend(Uri feedUri, AtomBase baseEntry, GDataRequestType type, AsyncSendData data)
   at Google.GData.Client.Service.Insert(Uri feedUri, AtomEntry newEntry, AsyncSendData data)
   at Google.GData.Photos.PicasaService.Insert[TEntry](Uri feedUri, TEntry entry)
   at GooglePhotoOrganizer.PicasaClient.CreateAlbum(String title, String description, Boolean isPublic) in D:\Git\GooglePhotoOrganizer\PicasaClient.cs:line 208

Inner Exception 1:
WebException: The remote server returned an error: (501) Not Implemented.

**Comment by Entonsky** [comment]
Have you got proxy server on your system. Is this adress https://picasaweb.google.com/data/feed/api/user/default available from your machine?

**Comment by Entonsky** [comment]
Unfortunatelly Google disable Picassa Web API to work with albums. So application can't work with it https://developers.google.com/picasa-web/docs/3.0/releasenotes.
